namespace F1Telemetry.Udp.Packets;

public sealed record MotionExPacket(
    WheelSet<float> SuspensionPosition,
    WheelSet<float> SuspensionVelocity,
    WheelSet<float> SuspensionAcceleration,
    WheelSet<float> WheelSpeed,
    WheelSet<float> WheelSlipRatio,
    WheelSet<float> WheelSlipAngle,
    WheelSet<float> WheelLateralForce,
    WheelSet<float> WheelLongitudinalForce,
    float HeightOfCogAboveGround,
    float LocalVelocityX,
    float LocalVelocityY,
    float LocalVelocityZ,
    float AngularVelocityX,
    float AngularVelocityY,
    float AngularVelocityZ,
    float AngularAccelerationX,
    float AngularAccelerationY,
    float AngularAccelerationZ,
    float FrontWheelsAngle,
    WheelSet<float> WheelVerticalForce,
    float FrontAeroHeight,
    float RearAeroHeight,
    float FrontRollAngle,
    float RearRollAngle,
    float ChassisYaw,
    float ChassisPitch,
    WheelSet<float> WheelCamber,
    WheelSet<float> WheelCamberGain) : IUdpPacket;
