namespace F1Telemetry.Udp.Packets;

public sealed record SessionPacket(
    byte Weather,
    sbyte TrackTemperature,
    sbyte AirTemperature,
    byte TotalLaps,
    ushort TrackLength,
    byte SessionType,
    sbyte TrackId,
    byte Formula,
    ushort SessionTimeLeft,
    ushort SessionDuration,
    byte PitSpeedLimit,
    bool GamePaused,
    bool IsSpectating,
    byte SpectatorCarIndex,
    bool SliProNativeSupport,
    byte NumMarshalZones,
    MarshalZoneData[] MarshalZones,
    byte SafetyCarStatus,
    bool NetworkGame,
    byte NumWeatherForecastSamples,
    WeatherForecastSampleData[] WeatherForecastSamples,
    byte ForecastAccuracy,
    byte AiDifficulty,
    uint SeasonLinkIdentifier,
    uint WeekendLinkIdentifier,
    uint SessionLinkIdentifier,
    byte PitStopWindowIdealLap,
    byte PitStopWindowLatestLap,
    byte PitStopRejoinPosition,
    bool SteeringAssist,
    byte BrakingAssist,
    byte GearboxAssist,
    bool PitAssist,
    bool PitReleaseAssist,
    bool ErsAssist,
    bool DrsAssist,
    byte DynamicRacingLine,
    byte DynamicRacingLineType,
    byte GameMode,
    byte RuleSet,
    uint TimeOfDay,
    byte SessionLength,
    byte SpeedUnitsLeadPlayer,
    byte TemperatureUnitsLeadPlayer,
    byte SpeedUnitsSecondaryPlayer,
    byte TemperatureUnitsSecondaryPlayer,
    byte NumSafetyCarPeriods,
    byte NumVirtualSafetyCarPeriods,
    byte NumRedFlagPeriods,
    bool EqualCarPerformance,
    byte RecoveryMode,
    byte FlashbackLimit,
    byte SurfaceType,
    bool LowFuelMode,
    bool RaceStarts,
    bool TyreTemperature,
    bool PitLaneTyreSim,
    byte CarDamage,
    byte CarDamageRate,
    byte Collisions,
    bool CollisionsOffForFirstLapOnly,
    bool MpUnsafePitRelease,
    bool MpOffForGriefing,
    byte CornerCuttingStringency,
    bool ParcFermeRules,
    byte PitStopExperience,
    byte SafetyCar,
    byte SafetyCarExperience,
    bool FormationLap,
    bool FormationLapExperience,
    byte RedFlags,
    bool AffectsLicenceLevelSolo,
    bool AffectsLicenceLevelMp,
    byte NumSessionsInWeekend,
    byte[] WeekendStructure,
    float Sector2LapDistanceStart,
    float Sector3LapDistanceStart,
    // 以下为 F1 26 新增字段（m_formula = 13）；F1 25 不包含，解析时填默认值。
    byte ActiveAeroTrackStatus = 0,
    byte NumActiveAeroZonesFull = 0,
    ActiveAeroZone[]? ActiveAeroZonesFull = null,
    byte NumActiveAeroZonesPartial = 0,
    ActiveAeroZone[]? ActiveAeroZonesPartial = null,
    byte NumDrsZones = 0,
    DRSZone[]? DrsZones = null,
    float StartReactionTime = 0,
    byte AntiLockBrakesAssist = 0,
    byte TractionControlAssist = 0,
    byte DynamicRacingLineHiVis = 0,
    byte DynamicRacingLineColourBlind = 0,
    byte RecurringRewindPrompt = 0) : IUdpPacket;

public sealed record MarshalZoneData(
    float ZoneStart,
    sbyte ZoneFlag);

/// <summary>F1 26 主动空气动力学激活区段；ZoneStart 和 ZoneEnd 均为 0 到 1 的单圈进度分数。</summary>
public sealed record ActiveAeroZone(
    float ZoneStart,
    float ZoneEnd);

/// <summary>F1 26 DRS 区段；ZoneStart 和 ZoneEnd 均为 0 到 1 的单圈进度分数。</summary>
public sealed record DRSZone(
    float ZoneStart,
    float ZoneEnd);

public sealed record WeatherForecastSampleData(
    byte SessionType,
    byte TimeOffset,
    byte Weather,
    sbyte TrackTemperature,
    sbyte TrackTemperatureChange,
    sbyte AirTemperature,
    sbyte AirTemperatureChange,
    byte RainPercentage);
